# Generated by Django 2.2.7 on 2019-11-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-created',)},
        ),
    ]
