# Generated by Django 2.2.7 on 2019-11-24 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191116_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14a97143-42db-4080-bbe6-b72624b65e4d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
