# Generated by Django 2.2.7 on 2019-11-24 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191124_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('L', 'Link'), ('N', 'Note'), ('M', 'Memo'), ('D', 'TODO')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c680fcf8-7a2e-4a3f-9342-1dbbb5233c52'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
